apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dd-managed-hdd-1g
  annotations:
    volume.beta.kubernetes.io/storage-class: managedhdd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi